main - Fixed make file dependencies and renamed target.

diff --git a/src/Makefile b/src/Makefile
--- a/src/Makefile
+++ b/src/Makefile
@@ -12,8 +12,9 @@ ATARI800 := $(ROOT)/../../code/atari800
 
 A8DISK := $(ROOT)/../disks/a8.atr
 A8BIN := AUTORUN.SYS
+RESOURCE_OUTPUT := generated/strings.m65 generated/ram.m65 generated/state.m65
 
-.PHONY: all run lint test build-resources assemble clean ensure-venv
+.PHONY: all run run-disk lint test build-resources assemble clean ensure-venv
 
 # This Makefile REQUIRES a Python virtualenv at `venv/.venv`.
 
@@ -25,27 +26,25 @@ ensure-venv:
 		echo "Installing requirements..."; \
 # Upgrade base packaging tools: pip=installer, setuptools/wheel=needed to build/install many packages \
 		$(VENV_PY) -m pip install --upgrade pip setuptools wheel || true; \
-		$(VENV_PY) -m pip install -r ../venv/requirements.txt || { echo "Failed to install requirements"; rm -rf $(VENV_DIR); exit 1; }; \
+		$(VENV_PY) -m pip install -r $(ROOT)/../venv/requirements.txt || { echo "Failed to install requirements"; rm -rf $(VENV_DIR); exit 1; }; \
 	else \
 		echo "Virtualenv already exists at $(VENV_DIR)"; \
 	fi
 
 all: run
 
-run: yahtzee.65o
-	$(ATARI800)  ${A8BIN}
+run: $(A8BIN)
+	$(ATARI800) $(A8BIN)
 
-run-disk: yahtzee.65o
-	$(ATARI800) ${A8DISK}
+run-disk: $(A8BIN)
+	$(ATARI800) $(A8DISK)
 
+$(A8BIN): hw_a8.m65 $(RESOURCE_OUTPUT) | ensure-venv
+	rm -f $(A8BIN)
+	$(ATASM) -x${A8DISK} -g/tmp/file.lst -o${A8BIN} ./hw_a8.m65
 
-yahtzee.65o: yahtzee.m65 $(RESOURCE_DIR)/resource_builder.py | ensure-venv
-	rm -f yahtzee.65o
-	rm -rf generated
-	rm -f a8*
-	$(MAKE) lint
+generated/strings.m65 generated/ram.m65 generated/state.m65: $(RESOURCE_DIR)/resource_builder.py | ensure-venv
 	$(VENV_PY) $(RESOURCE_DIR)/resource_builder.py
-	$(ATASM) -x${A8DISK} -g/tmp/file.lst  -o${A8BIN} ./yahtzee.m65
 
 lint: | ensure-venv
 	$(RUFF) format $(RESOURCE_DIR)
@@ -55,12 +54,10 @@ lint: | ensure-venv
 test: | ensure-venv
 	PYTHONPATH=$(RESOURCE_DIR) $(VENV_PY) -m unittest discover -s $(RESOURCE_DIR)/tests -p "test_*.py"
 
-build-resources: yahtzee.65o
+build-resources: $(RESOURCE_OUTPUT)
 
-assemble:
-	$(ATASM) -xd2.atr -g/tmp/file.lst ./yahtzee.m65
 
 clean:
-	rm -f ${A8BIN}
+	rm -f $(A8BIN)
 	rm -rf generated
 	rm -f a8*
